import cv2
import matplotlib.pyplot as plt
import numpy as np

img1 = cv2.imread("../datasets/bunga1.jpg", 0)
img2 = cv2.imread("../datasets/bunga2.jpg", 0)
img3 = cv2.imread("../datasets/bunga3.jpg", 0)

def ekualisasiH(img_src):
    return cv2.equalizeHist(img_src)

def histGambar(img_src):
    hist, bins = np.histogram(img_src.flatten(), 256, [0, 256])
    return hist

def cdfGambar(hist_src):
    cdf = hist_src.cumsum()
    cdf_normalized = cdf * float(hist_src.max()) / cdf.max()
    return cdf_normalized

# gambar 1
plt.subplot(6, 3, 1)
plt.imshow(img1, cmap = 'gray', vmin = 0, vmax = 255)
plt.title('Citra Gray 1')
plt.axis('off')
plt.subplot(6, 3, 2)
plt.hist(img1.flatten(), 256, [0, 256], color='r')
plt.title('Histogram Gray 1')
plt.subplot(6, 3, 3)
hist = histGambar(img1)
cdf = cdfGambar(hist)
plt.plot(cdf, color="b")
plt.title('CDF 1')
plt.subplot(6, 3, 4)
img_eq = ekualisasiH(img1)
plt.imshow(img_eq, cmap = 'gray', vmin = 0, vmax = 255)
plt.title('Citra Equalisasi 1')
plt.axis('off')
plt.subplot(6, 3, 5)
plt.hist(img_eq.flatten(), 256, [0, 256], color='r')
plt.title('Histogram Equalisasi 1')
plt.subplot(6, 3, 6)
hist = histGambar(img_eq)
cdf = cdfGambar(hist)
plt.plot(cdf, color="b")
plt.title('CDF 1')

# # gambar 2
plt.subplot(6, 3, 7)
plt.imshow(img2, cmap = 'gray', vmin = 0, vmax = 255)
plt.title('Citra Gray 1')
plt.axis('off')
plt.subplot(6, 3, 8)
plt.hist(img2.flatten(), 256, [0, 256], color='r')
plt.title('Histogram Gray 1')
plt.subplot(6, 3, 9)
hist = histGambar(img2)
cdf = cdfGambar(hist)
plt.plot(cdf, color="b")
plt.title('CDF 1')
plt.subplot(6, 3, 10)
img_eq = ekualisasiH(img2)
plt.imshow(img_eq, cmap = 'gray', vmin = 0, vmax = 255)
plt.title('Citra Equalisasi 1')
plt.axis('off')
plt.subplot(6, 3, 11)
plt.hist(img_eq.flatten(), 256, [0, 256], color='r')
plt.title('Histogram Equalisasi 1')
plt.subplot(6, 3, 12)
hist = histGambar(img_eq)
cdf = cdfGambar(hist)
plt.plot(cdf, color="b")
plt.title('CDF 1')

# # gambar3
plt.subplot(6, 3, 13)
plt.imshow(img3, cmap = 'gray', vmin = 0, vmax = 255)
plt.title('Citra Gray 1')
plt.axis('off')
plt.subplot(6, 3, 14)
plt.hist(img3.flatten(), 256, [0, 256], color='r')
plt.title('Histogram Gray 1')
plt.subplot(6, 3, 15)
hist = histGambar(img3)
cdf = cdfGambar(hist)
plt.plot(cdf, color="b")
plt.title('CDF 1')
plt.subplot(6, 3, 16)
img_eq = ekualisasiH(img3)
plt.imshow(img_eq, cmap = 'gray', vmin = 0, vmax = 255)
plt.title('Citra Equalisasi 1')
plt.axis('off')
plt.subplot(6, 3, 17)
plt.hist(img_eq.flatten(), 256, [0, 256], color='r')
plt.title('Histogram Equalisasi 1')
plt.subplot(6, 3, 18)
hist = histGambar(img_eq)
cdf = cdfGambar(hist)
plt.plot(cdf, color="b")
plt.title('CDF 1')

plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()